/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NewProject;

public class Geometry {
    public boolean someLibraryMethod() {
        return true;
    }
   
    float areaRect(float width, float height) {

        return width * height;
    }

    float perimeterRect(float width, float height) {
        return width + width + height + height;
    }

    float volumeSphere(float radius) {

        return (float) (Math.PI * Math.pow(radius, 3) * 4 / 3);
    }

    float surfaceAreaSphere(float radius) {
        return (float) (4 * Math.PI * Math.pow(radius, 2));
    }
}
